import React from 'react';
import {
  Activity,
  AppWindow,
  ChartNoAxesCombined,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleCheck,
  CircleDot,
  CircleHelp,
  Code2,
  Copy,
  Cpu,
  Download,
  Ellipsis,
  ExternalLink,
  FileCode,
  Folder,
  FolderKanban,
  Globe2,
  Info,
  Layers,
  LayoutDashboard,
  Link2,
  ListTodo,
  Maximize2,
  Minimize2,
  Minus,
  Monitor,
  Moon,
  Package,
  PanelLeftClose,
  PanelLeftOpen,
  Pause,
  Play,
  Plus,
  Puzzle,
  RefreshCw,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Terminal,
  Timer,
  Trash2,
  TriangleAlert,
  Wrench,
  X
} from 'lucide-react';

const h = React.createElement;

const ICONS = Object.freeze({
  add: Plus,
  check: Check,
  circle: Circle,
  circleDot: CircleDot,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  close: X,
  externalLink: ExternalLink,
  folder: Folder,
  info: Info,
  light: Sun,
  dark: Moon,
  pause: Pause,
  play: Play,
  refresh: RefreshCw,
  system: Monitor,
  warning: TriangleAlert,
  home: LayoutDashboard,
  tasks: ListTodo,
  code: Code2,
  browser: Globe2,
  workspaces: FolderKanban,
  activity: Activity,
  preferences: SlidersHorizontal,
  application: AppWindow,
  about: CircleHelp,
  connection: Link2,
  processes: Terminal,
  terminal: Terminal,
  tools: Wrench,
  diagnostics: TriangleAlert,
  usage: ChartNoAxesCombined,
  extensions: Puzzle,
  settings: Settings,
  search: Search,
  more: Ellipsis,
  sidebarClose: PanelLeftClose,
  sidebarOpen: PanelLeftOpen,
  minimize: Minus,
  maximize: Maximize2,
  restore: Minimize2,
  reliability: ShieldCheck,
  success: CircleCheck,
  help: CircleHelp,
  timer: Timer,
  copy: Copy,
  cpu: Cpu,
  download: Download,
  fileCode: FileCode,
  layers: Layers,
  package: Package,
  shield: Shield,
  sparkles: Sparkles,
  trash: Trash2
});

export function Icon({ name, className = '', size = 18, strokeWidth = 1.8, ...props }) {
  const Component = ICONS[name] || CircleHelp;
  return h(Component, {
    className: ['ui-icon', className].filter(Boolean).join(' '),
    size,
    strokeWidth,
    'aria-hidden': 'true',
    focusable: 'false',
    ...props
  });
}
