const GOAL_MODE_RESOURCE_URI = 'ui://relai/goal-continuation-v1.html';
const GOAL_MODE_RESOURCE_MIME_TYPE = 'text/html;profile=mcp-app';
const GOAL_CONTINUATION_DELAY_MS = 20 * 60 * 1000;
const GOAL_UI_PROTOCOL_VERSION = '2026-01-26';

export {
  GOAL_CONTINUATION_DELAY_MS,
  GOAL_MODE_RESOURCE_MIME_TYPE,
  GOAL_MODE_RESOURCE_URI,
  GOAL_UI_PROTOCOL_VERSION
};
